version: '3.4'

services:
  search4all:
    image: docker.io/fatwang2/search4all
    restart: unless-stopped
    ports:
      - 8800:8800
    environment:
      OPENAI_API_KEY: sk-xxx
      OPENAI_BASE_URL: https://api.openai.com/v1
      LLM_MODEL: gpt-3.5-turbo-0125
      RELATED_QUESTIONS: 1
      # Change your search provider name here, if use another different provider
      BACKEND: SEARCH1API
      # Set your search key from your provider here
      SEARCH1API_KEY: xxxx
      # SYSTEM_PROMPT: "You are a trustworthy and experienced AI assistant, please always use Chinese to answer the following questions with a bullet list: {context}"
      # RELATED_QUESTIONS_SYSTEM_PROMPT: "xxx {context} xxx"
